# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/kbookmarks': '@stable'
    'frameworks/threadweaver': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/karchive': '@stable'
    'frameworks/khtml': '@stable'
    'frameworks/kjs': '@stable'
    'libraries/phonon': '@stable'
    'graphics/libkexiv2': '@stable'
    'graphics/kdegraphics-mobipocket': '@stable'
